CREATE TABLE Employees(
eid INT AUTO_INCREMENT, 
name VARCHAR(50) NOT NULL, 
email VARCHAR(30), 
role VARCHAR(30) NOT NULL, 
address VARCHAR(30) NOT NULL,
phone VARCHAR(30) NOT NULL,
PRIMARY KEY(eid)
);